baseURL: "https://nufflee.github.io/blog"
title: Nufflee's Blog
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Nufflee's Blog
  description: "Nufflee's Blog about programming, electronics, FPGAs, SDRs and more"
  author: Nufflee

  images: ["/blog/cropega.png"]

  ShowReadingTime: true
  ShowShareButtons: true
  comments: false
  defaultTheme: dark
  disableThemeToggle: false
  disableSpecial1stPost: false

  assets:
    favicon: /blog/favicon.png
    favicon32x32: /blog/favicon.png
    favicon16x16: /blog/favicon.png

  label:
    text: Home
    iconHeight: 35

  # home-info mode
  homeInfoParams:
    Title: Hi there 👋
    Content: I’m Nufflee, a 17 yo programmer from Croatia and this is my epic (soon-to-be) blog about programming, electronics, FPGAs, SDRs and more!

  socialIcons:
    - name: twitter
      url: https://twitter.com/nufflee
    - name: github
      url: https://github.com/nufflee
    - name: twitch
      url: https://twitch.com/nufflee
    - name: discord
      url: https://discord.gg/wNheug4